"""Write the Russian string table as windows-1251 (the game reads text/rus in that encoding;
a UTF-8 file shows garbage). Run after changing a string here."""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "gamedata", "configs", "text", "rus", "st_arsenal.xml")

STRINGS = [
    ("st_arsenal_title", "Арсенал"),
    ("st_arsenal_cat_pistols", "Пистолеты"),
    ("st_arsenal_cat_smgs", "ПП"),
    ("st_arsenal_cat_shotguns", "Дробовики"),
    ("st_arsenal_cat_rifles", "Автоматы"),
    ("st_arsenal_cat_snipers", "Снайперские"),
    ("st_arsenal_cat_launchers", "Гранатомёты"),
    ("st_arsenal_cat_melee", "Холодное"),
    ("st_arsenal_fire_modes", "Режимы огня"),
    ("st_arsenal_found_count", "Найдено %s из %s"),
    ("st_arsenal_found_on", "Найдено %s: %s"),
    ("st_arsenal_not_found", "Ещё не найдено"),
    ("st_arsenal_found_only", "Только найденные"),
    ("st_arsenal_new_entry", "Новое в Арсенале: %s"),
    ("st_arsenal_back", "Назад"),
    ("st_arsenal_variants", "Варианты:"),
    ("st_arsenal_variant_found", "%s, найдено %s: %s"),
    ("st_arsenal_max", "макс. %s"),
    ("st_arsenal_scopes", "Прицелы:"),
    ("st_arsenal_suppressors", "Глушители:"),
    ("st_arsenal_accessories", "Аксессуары:"),
    ("st_arsenal_parts", "Детали:"),
    ("st_arsenal_builtin", "Встроенный"),
    ("st_arsenal_builtin_on", "Встроенный: %s"),
    ("st_arsenal_builtin_gl", "Встроенный гранатомёт"),
    ("st_arsenal_builtin_gl_on", "Встроенный гранатомёт: %s"),
    ("st_arsenal_builtin_laser", "Встроенный лазер"),
    ("st_arsenal_builtin_laser_on", "Встроенный лазер: %s"),
    ("st_arsenal_makes", "превращает в %s"),
    ("st_arsenal_modes_by_upgrade", "%s (%s после улучшения)"),
    ("st_arsenal_ammo_by_upgrade", "После улучшения: %s"),
    ("st_arsenal_after_upgrade", "после улучшения"),
    ("st_arsenal_magazines", "Магазины:"),
    ("st_arsenal_rounds", "%s патр."),
    ("ui_mcm_menu_arsenal", "Арсенал"),
    ("ui_mcm_arsenal_flat_key", "Открыть Арсенал отдельно"),
    ("ui_mcm_arsenal_flat_key_desc", "Открывает Арсенал в отдельном окне, вне КПК."),
    ("ui_mcm_arsenal_about", "С трёхмерным КПК его страницы выводятся на экран в руке, и значки теряют чёткость. "
                             "По этой клавише Арсенал выводится прямо на экран, так же чётко, как инвентарь."),
    ("st_arsenal_where", "Где найти:"),
    ("st_arsenal_repair_kits", "Ремкомплекты:"),
    ("st_arsenal_carried_by", "Встречается у:"),
    ("st_arsenal_rank_range", "%s – %s"),
    ("st_arsenal_all_ranks", "все ранги"),
    ("st_arsenal_special", "спецотряды"),
    ("st_arsenal_stashes", "В тайниках"),
    ("st_arsenal_no_source", "Не встречается ни у группировок, ни в тайниках"),
    ("st_arsenal_nimble_from", "У Шустрого, за %s и %s руб."),
    ("st_arsenal_nimble_gets", "Шустрый даёт %s за него и %s руб."),
    ("st_arsenal_made_from", "Собирается: %s + %s"),
    ("st_arsenal_start_kit", "Стартовый набор, %s очков: %s"),
    ("st_arsenal_start_free", "Стартовый набор, бесплатно: %s"),
    ("st_arsenal_start_eco", "%s; только %s"),
    ("st_arsenal_every_faction", "все группировки"),
    ("st_arsenal_camos", "Камуфляж:"),
    ("st_arsenal_camo_found", "Обнаружен"),
    ("st_arsenal_camo_locked", "Ещё не обнаружен"),
    ("st_arsenal_camo_locked_on", "Ещё не обнаружен; бывает на оружии: %s"),
    ("st_arsenal_and_more", "%s и ещё %s"),
    ("ui_mcm_arsenal_count_seen", "Учитывать увиденное оружие"),
    ("ui_mcm_arsenal_count_seen_desc", "Учитывать также оружие в трупе, тайнике или у торговца, когда вы их открываете, а не только то, что вы забрали."),
    ("st_arsenal_risk", "Улучшения R.I.S.K.:"),
    ("st_arsenal_risk_note", "Одно на оружии в исходном виде, от слабого к сильному"),
    ("st_arsenal_risk_bad", "%s (неудача: %s)"),
    ("st_arsenal_risk_same", "на карточке без изменений"),
    ("st_arsenal_risk_accuracy", "Точность"),
    ("st_arsenal_risk_handling", "Удобность"),
    ("st_arsenal_risk_sway", "Раскачка"),
    ("st_arsenal_risk_fire_rate", "Скорострельность"),
    ("st_arsenal_risk_velocity", "Скорость пули"),
    ("st_arsenal_risk_reliability", "Надёжность"),
    ("st_arsenal_risk_recoil", "Контроль отдачи"),
    ("st_arsenal_risk_weight", "Вес"),
    ("st_arsenal_risk_damage", "Урон"),
    # tags for guns that share a name; stat words as the Russian stat card has them
    ("st_arsenal_tag_suppressed", "с глушителем"),
    ("st_arsenal_tag_scoped", "с прицелом"),
    ("st_arsenal_tag_gl", "с ПГ"),
    ("st_arsenal_tag_gl_mount", "под ПГ"),
    ("st_arsenal_tag_auto", "авто"),
    ("st_arsenal_tag_rounds", "%s патр."),
    ("st_arsenal_tag_rpm", "%s ВВМ"),
    ("st_arsenal_tag_accuracy", "точность %s"),
    ("st_arsenal_tag_handling", "удобность %s"),
    ("st_arsenal_tag_damage", "урон %s"),
    ("st_arsenal_tag_speed", "%s м/с"),
    ("st_arsenal_tag_reliability", "надёжность %s"),
    ("st_arsenal_tag_recoil", "контроль отдачи %s"),
    ("st_arsenal_tag_sup_mount", "под глушитель"),
    ("st_arsenal_tag_scope_mount", "под прицел"),
    ("st_arsenal_cat_light", "Лёгкая броня"),
    ("st_arsenal_cat_medium", "Средняя броня"),
    ("st_arsenal_cat_heavy", "Тяжёлая броня"),
    ("st_arsenal_cat_exo", "Экзоскелеты"),
    ("st_arsenal_cat_helmets", "Шлемы"),
    ("st_arsenal_worn_by", "Носят:"),
    ("st_arsenal_drop_chance", "Выпадает с тела в %s случаев"),
    ("st_arsenal_drop_rank", "Выпадает с тела в %s случаев, если ваш ранг не ниже %s (%s)"),
    ("st_arsenal_drop_off", "В этой экономике броня с тел не выпадает"),
    ("st_arsenal_exchange_gets", "У %s: за любой из %s костюмов и %s руб. (только %s)"),
    ("st_arsenal_exchange_takes", "%s отдаёт за него %s и %s руб. (только %s)"),
    ("st_arsenal_rumor_ask", "Не видел в последнее время чего-нибудь стоящего из снаряжения?"),
    ("st_arsenal_rumor", "Видел недавно: у бойцов группировки «%s» есть %s."),
    ("st_arsenal_rumor_specs", "Видел недавно: у бойцов группировки «%s» есть %s. Хорошая вещь, расскажу, на что она способна."),
    ("st_arsenal_rumor_none", "Ничего такого, о чём стоит рассказать."),
    ("st_arsenal_gunsmith_ask", "Знаешь какие-нибудь особенные стволы?"),
    ("st_arsenal_gunsmith_offer", "Есть один, о котором ты ещё не слышал. Что это и как его достать: %s руб."),
    ("st_arsenal_gunsmith_yes", "Договорились."),
    ("st_arsenal_gunsmith_no", "Не сейчас."),
    ("st_arsenal_gunsmith_told", "Это %s. Подробности скинул тебе на КПК."),
    ("st_arsenal_learned", "Узнано (%s): %s"),
    ("st_arsenal_by_kill", "боец группировки «%s»"),
    ("st_arsenal_by_body", "тело бойца группировки «%s»"),
    ("st_arsenal_by_pda", "КПК группировки «%s»"),
    ("st_arsenal_by_tally", "бои с группировкой «%s»"),
    ("st_arsenal_by_stash", "тайник"),
    ("st_arsenal_by_start", "своя группировка"),
    ("st_arsenal_by_found", "находка"),
    ("st_arsenal_by_someone", "кто-то"),
    ("st_arsenal_known_count", "Известно %s · Найдено %s из %s"),
    ("st_arsenal_by_faction", "По группировкам"),
    ("st_arsenal_known_new_count", "Известно %s · Найдено %s из %s · новых: %s"),
    ("st_arsenal_learned_on", "Узнано %s: %s"),
    ("st_arsenal_not_studied", "Ещё не изучено: найдите экземпляр или узнайте его характеристики у знающих, чтобы увидеть параметры и совместимость"),
    ("st_arsenal_where_unknown", "Пока ничего не известно о том, где его найти"),
    ("st_arsenal_never", "В этой игре не встречается"),
    ("st_arsenal_sold_by", "Продаётся у торговцев"),
    ("st_arsenal_sold_at", "Видели в продаже: %s"),
    ("st_arsenal_stashes_seen", "Видели в тайниках: %s"),
    ("st_arsenal_in_bodies", "Иногда попадается на телах бойцов"),
    ("st_arsenal_from_tasks", "За задания"),
    ("st_arsenal_from_gift", "Сюжетная награда"),
    ("st_arsenal_from_craft", "Изготавливается на верстаке"),
    ("st_arsenal_from_homestead", "В вылазках за тайниками (Homestead)"),
    ("st_arsenal_carried_story", "Носит: %s"),
    ("st_arsenal_carried_story_some", "Носят сюжетные персонажи"),
    ("st_arsenal_rolled", "У некоторых бойцов %s приходит уже переделанным в него"),
    ("st_arsenal_addon_never", "не встречается"),
    ("ui_mcm_arsenal_jailbreak", "Взлом: показать всё"),
    ("ui_mcm_arsenal_jailbreak_desc", "Арсенал показывает то, о чём вы узнали: снаряжение своей группировки с самого начала, затем найденное, увиденное, добытое, прочитанное в КПК и услышанное от людей. Со взломом он показывает всё, что есть в этой игре, как законченная энциклопедия."),
    ("st_arsenal_cat_ammo", "Патроны"),
    ("st_arsenal_tag_ap", "проб. %s"),
    ("st_arsenal_tag_hit", "урон x%s"),
    ("st_arsenal_times", "x%s"),
    ("st_arsenal_hit_power", "Мощность выстрела: %s"),
    ("st_arsenal_jam_worn", "Вероятность клина: %s на выстрел при состоянии деталей ниже 80%%"),
    ("st_arsenal_jam_both", "Вероятность клина: %s на выстрел, %s при состоянии деталей ниже 80%%"),
    ("st_arsenal_jam_base", "Вероятность клина: %s на выстрел"),
    ("st_arsenal_jam_none", "Вероятность клина: нет"),
    ("st_arsenal_round_damage", "Урон"),
    ("st_arsenal_round_ap", "Бронепробитие"),
    ("st_arsenal_round_speed", "Скорость пули"),
    ("st_arsenal_round_pellets", "Дробин"),
    ("st_arsenal_round_kept", "Остаётся на 50/100/200 м"),
    ("st_arsenal_fired_by", "Используется в:"),
    ("st_arsenal_col_round", "Патрон"),
    ("st_arsenal_col_damage", "Урон"),
    ("st_arsenal_col_ap", "Проб."),
    ("st_arsenal_col_speed", "м/с"),
    ("st_arsenal_col_kept", "100 м"),
    ("st_arsenal_pellets", "%s x %s"),
    ("st_arsenal_rounds_note", "Урон из этого оружия, бронепробитие (проб.), скорость пули и урон, остающийся на 100 м."),
    ("st_arsenal_ammo_other", "Другие варианты: %s"),
    ("st_arsenal_vs_bullets", "Против пуль:"),
    ("st_arsenal_pen_range", "Держит патроны до %s (проб. %s); %s (проб. %s) и сильнее пробивают."),
    ("st_arsenal_pen_all", "Держит все встречающиеся патроны, сильнейший — %s (проб. %s)."),
    ("st_arsenal_pen_none", "Пробивается любым патроном, начиная с %s (проб. %s)."),
    ("st_arsenal_pen_count", "Держит %s из %s встречающихся патронов."),
    ("st_arsenal_pen_damage", "Попадание наносит %s урона, если броня держит, и %s, если пробита."),
    ("st_arsenal_sold_tiers", "Продаётся у торговцев:"),
    ("st_arsenal_tier", "Уровень %s: %s"),
    ("st_arsenal_tier_need", "Уровень %s, %s: %s"),
    ("st_arsenal_need_goodwill", "репутация %s"),
    ("st_arsenal_need_kit", "после набора инструментов"),
    ("st_arsenal_need_kits", "после %s наборов инструментов"),
    ("st_arsenal_need_drugkit", "после набора медикаментов"),
    ("st_arsenal_need_story", "дальше по сюжету"),
    ("st_arsenal_need_heavy", "Тяжёлые карманы"),
    ("st_arsenal_or", "или"),
    ("st_arsenal_trade_barman", "бармены"),
    ("st_arsenal_trade_mechanic", "техники"),
    ("st_arsenal_trade_medic", "медики"),
    ("st_arsenal_trade_other", "другие торговцы"),
    ("st_arsenal_stashes_odds", "В тайниках: %s"),
    ("st_arsenal_stash_odds", "%s %s"),
    ("st_arsenal_stash_odds_rare", "%s %s (редкие %s)"),
    ("st_arsenal_stash_odds_note", "Шанс найти его в одном тайнике там."),
]


def main():
    lines = ['<?xml version="1.0" encoding="windows-1251"?>', "<string_table>"]
    for sid, text in STRINGS:
        lines += ['\t<string id="%s">' % sid, "\t\t<text>%s</text>" % text, "\t</string>"]
    lines.append("</string_table>")
    data = ("\r\n".join(lines) + "\r\n").encode("cp1251")
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "wb") as f:
        f.write(data)
    print(len(STRINGS), "strings ->", OUT)


if __name__ == "__main__":
    main()
